In [1]:
#Down-sampling and up-sampling using python 

import numpy as np
import cv2

# Example 4x4 grayscale image (matrix with pixel values)
image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
], dtype=np.uint8)

print("Original 4x4 Matrix:\n", image)

# ---- Downsampling (reduce size) ----
# Reduce 4x4 -> 2x2 using INTER_NEAREST (nearest neighbor)
downsampled = cv2.resize(image, (2, 2), interpolation=cv2.INTER_NEAREST)
print("\nDownsampled 2x2 Matrix:\n", downsampled)

# ---- Upsampling (increase size) ----
# Upsample 4x4 -> 8x8 using INTER_NEAREST
upsampled = cv2.resize(image, (8, 8), interpolation=cv2.INTER_NEAREST)
print("\nUpsampled 8x8 Matrix:\n", upsampled)


Original 4x4 Matrix:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Downsampled 2x2 Matrix:
 [[ 10  30]
 [ 90 110]]

Upsampled 8x8 Matrix:
 [[ 10  10  20  20  30  30  40  40]
 [ 10  10  20  20  30  30  40  40]
 [ 50  50  60  60  70  70  80  80]
 [ 50  50  60  60  70  70  80  80]
 [ 90  90 100 100 110 110 120 120]
 [ 90  90 100 100 110 110 120 120]
 [130 130 140 140 150 150 160 160]
 [130 130 140 140 150 150 160 160]]
